### ISSUE TITLE
How to install on OS Linux

### ISSUE THREAD

**Issue by ateproni** [vudung45/HLS-GoogleDrive#13]
Hi, how to install this repo on Unix / Linux OS?  When I run it, get an error "UnhandledRejectionWarning: MongoParseError: invalid connection string ....."

**Comment by lucasferrari3** [comment]
> Hi, how to install this repo on Unix / Linux OS? When I run it, get an error "UnhandledRejectionWarning: MongoParseError: invalid connection string ....."

You have to add the database url, take a look at MongoDB Atlas
